[package]
name = "ik_lgp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.6"
rand = "0.8.5"
rayon = "1.7.0"
